services:
  cryptomator-webdav: &base
    build:
      context: .
      dockerfile: Dockerfile
    image: greycubesgav/cryptomator-webdav
    container_name: cryptomator-webdav
    env_file:
      - ./vault.env
    ports:
      # Bind to the internal interface of the host
      # Change me to remove '127.0.0.1:' to access the webdav share on the host's local network.
      - "127.0.0.1:${CRYPTOMATOR_PORT}:8443/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${CRYPTOMATOR_VAULT_SRC_PATH}:/vault:rw"
  cryptomator-webdav-passfile:
    # Adds passfile mount to container
    <<: *base
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${CRYPTOMATOR_VAULT_SRC_PATH}:/vault:rw"
      - "${CRYPTOMATOR_VAULT_PASSFILE}:/vault.pass:ro"
  cryptomator-webdav-dev: &dev
    # Used for local login and debugging of init scripts
    <<: *base
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${CRYPTOMATOR_VAULT_SRC_PATH}:/vault:rw"
      - './scripts/entrypoint.sh:/entrypoint.sh:ro'
      - './scripts/init.sh:/init.sh:ro'
    entrypoint: /usr/bin/env sh
  cryptomator-webdav-passfile-dev:
    # Adds passfile mount to dev container
    <<: *dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "${CRYPTOMATOR_VAULT_SRC_PATH}:/vault:rw"
      - "${CRYPTOMATOR_VAULT_PASSFILE}:/vault.pass:ro"
      - './scripts/entrypoint.sh:/entrypoint.sh:ro'
      - './scripts/init.sh:/init.sh:ro'
  cryptomator-webdav-env:
    <<: *base
    entrypoint: /usr/bin/env sh -c 'export | grep CRYPTOMATOR_'
