services:
  cryptomator-webdav: &base
    build:
      context: .
      dockerfile: Dockerfile
    image: greycubesgav/cryptomator-cli-docker
    user: 1000:1000
    environment:
      CRYPTOMATOR_VAULT_SRC_PATH: "${CRYPTOMATOR_VAULT_SRC_PATH}"
      CRYPTOMATOR_VAULT_NAME: "${CRYPTOMATOR_VAULT_NAME}"
      CRYPTOMATOR_VAULT_PASS: "${CRYPTOMATOR_VAULT_PASS}"
      CRYPTOMATOR_PORT: "${CRYPTOMATOR_PORT}"
    ports:
      - "127.0.0.1:${CRYPTOMATOR_PORT}:${CRYPTOMATOR_PORT}/tcp"
    volumes:
      - "${CRYPTOMATOR_VAULT_SRC_PATH}:/vault"
  cryptomator-webdav-dev:
      <<: *base
      entrypoint: /bin/bash
  cryptomator-webdav-env:
      <<: *base
      entrypoint: /bin/bash -c 'export | grep CRYPTOMATOR_'
